### ISSUE TITLE
Type Annotations

### ISSUE THREAD

**Issue by ThomasThelen** [daucheng/61A#1]
Hey I saw that you're doing some python learning. You probably haven't gotten to type annotations yet, but it would be a great time to start! If you want an example I can issue a pull request to one of your labs :)

Example:
`def make_city(name: str, lat: float, lon: float)->List:`

**Comment by daucheng** [comment]
Thanks for your reminder. 
I know annotations are important and useful but still not used to type it.
I will start to form a good habit of coding by typing annotations and would be really appreciate if you could show me some example as a role model.
Thank you for any help you can provide.
